name: find_thing
description: Application for localization things in home

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
#  route
  auto_route: ^3.2.4
#  internationalization
  intl: ^0.17.0
#  code
  flutter_bloc: ^8.0.1
  dartz: ^0.10.1
  equatable: ^2.0.3
  get_it: ^7.2.0
  objectbox: ^1.4.1
  objectbox_flutter_libs: any
  freezed_annotation: ^1.1.0
  uuid: ^3.0.6
#  test
  mockito: ^5.1.0
#  device
  image_picker: ^0.8.4+11
  path_provider: ^2.0.9
  permission_handler: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.8
  bloc_test: ^9.0.3
  objectbox_generator: any
  freezed: ">=1.0.0 <1.1.1"


flutter:
  uses-material-design: true

