// Mocks generated by Mockito 5.1.0 from annotations
// in find_thing/test/src/domain/use_cases/save_place_use_case_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;
import 'dart:ui' as _i8;

import 'package:dartz/dartz.dart' as _i2;
import 'package:find_thing/src/core/failure.dart' as _i6;
import 'package:find_thing/src/domain/entities/area.dart' as _i10;
import 'package:find_thing/src/domain/entities/place.dart' as _i3;
import 'package:find_thing/src/domain/repositories/database_repository.dart'
    as _i9;
import 'package:find_thing/src/domain/repositories/file_repository.dart' as _i4;
import 'package:image_picker/image_picker.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakePlace_1 extends _i1.Fake implements _i3.Place {}

/// A class which mocks [FileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileRepository extends _i1.Mock implements _i4.FileRepository {
  MockFileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.XFile>> pickImage(
          _i7.ImageSource? imageSource) =>
      (super.noSuchMethod(Invocation.method(#pickImage, [imageSource]),
              returnValue: Future<_i2.Either<_i6.Failure, _i7.XFile>>.value(
                  _FakeEither_0<_i6.Failure, _i7.XFile>()))
          as _i5.Future<_i2.Either<_i6.Failure, _i7.XFile>>);
  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.XFile>> retrieveLostImage() =>
      (super.noSuchMethod(Invocation.method(#retrieveLostImage, []),
              returnValue: Future<_i2.Either<_i6.Failure, _i7.XFile>>.value(
                  _FakeEither_0<_i6.Failure, _i7.XFile>()))
          as _i5.Future<_i2.Either<_i6.Failure, _i7.XFile>>);
  @override
  _i5.Future<String> saveImage({_i8.Image? image, String? uid}) =>
      (super.noSuchMethod(
          Invocation.method(#saveImage, [], {#image: image, #uid: uid}),
          returnValue: Future<String>.value('')) as _i5.Future<String>);
  @override
  _i5.Future<void> deleteImage(String? path) =>
      (super.noSuchMethod(Invocation.method(#deleteImage, [path]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
}

/// A class which mocks [DatabaseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseRepository extends _i1.Mock
    implements _i9.DatabaseRepository {
  MockDatabaseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Place> createNewPlace({String? name}) =>
      (super.noSuchMethod(Invocation.method(#createNewPlace, [], {#name: name}),
              returnValue: Future<_i3.Place>.value(_FakePlace_1()))
          as _i5.Future<_i3.Place>);
  @override
  _i5.Future<int> savePlace(_i3.Place? place) =>
      (super.noSuchMethod(Invocation.method(#savePlace, [place]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<bool> removePlace(int? id) =>
      (super.noSuchMethod(Invocation.method(#removePlace, [id]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<_i5.Stream<dynamic>> getPlacesStream() =>
      (super.noSuchMethod(Invocation.method(#getPlacesStream, []),
              returnValue:
                  Future<_i5.Stream<dynamic>>.value(Stream<dynamic>.empty()))
          as _i5.Future<_i5.Stream<dynamic>>);
  @override
  _i5.Future<int> saveArea(_i10.Area? area) =>
      (super.noSuchMethod(Invocation.method(#saveArea, [area]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<bool> removeArea(int? id) =>
      (super.noSuchMethod(Invocation.method(#removeArea, [id]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
}
